<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'help' => null,
    'silentExitOnException' => null,
    'sourcePath' => '@backend',
    'messagePath' => '@backend/messages',
    'languages' => [
        'ru' => ['locale' => 'ru-RU','name' => 'Русский'],
        'en' => [ 
            ['locale' => 'en-EN','name' => 'English'],
            // ['locale' => 'en-US','name' => 'USA'],
        ],
        // 'fr' => ['locale' => 'fr-FR', 'name' => 'France'],
        // 'gr' => ['locale' => 'gr-GR', 'name' => 'Germany'],
    ],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => true,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
        '/vendor',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'db',
    'db' => 'db',    
    'sourceMessageTable' => '{{%i18n_source_message}}',    
    'messageTable' => '{{%i18n_message}}',
    'localeTable' => '{{%i18n_locale}}',    
    'categoryTable' => '{{%i18n_category}}',
    'catalog' => 'messages',
    'ignoreCategories' => ['yii'],
    'phpFileHeader' => '',
    'phpDocBlock' => null,
];
